image: python:3.11

stages:
  - linting
  - black
  - test

before_script:
  - pip install -r requirements/test.txt

flake8:
  stage: linting
  script:
    - flake8 --verbose foosh

black:
  stage: black
  script:
    - black --config pyproject.toml --check foosh

django:
  stage: test
  script:
    - cd foosh
    - python manage.py test
