# Generated by Django 4.2.9 on 2024-04-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    (1, "bakery"),
                    (2, "drinks"),
                    (3, "hot"),
                    (4, "combo"),
                ],
                default=1,
                max_length=16,
                verbose_name="категория",
            ),
            preserve_default=False,
        ),
    ]
