# Generated by Django 4.2.9 on 2024-04-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("выпечка", "bakery"),
                    ("напитки", "drinks"),
                    ("горячее", "hot"),
                    ("комбо", "combo"),
                ],
                default="выпечка",
                max_length=16,
                verbose_name="категория",
            ),
            preserve_default=False,
        ),
    ]
