# Generated by Django 4.2.9 on 2024-04-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "bakery"),
                    (2, "drinks"),
                    (3, "hot"),
                    (4, "combo"),
                ],
                verbose_name="категория",
            ),
        ),
    ]
