# Generated by Django 4.2.9 on 2024-04-18 12:33

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                upload_to="catalog/", verbose_name="изображение"
            ),
        ),
    ]
