# Generated by Django 4.2.9 on 2024-04-20 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_school_options_alter_student_options"),
        ("catalog", "0005_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="users.school",
                verbose_name="школа",
            ),
        ),
    ]
