# Generated by Django 4.2.9 on 2024-04-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_school_customuser_is_school_customuser_is_student_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="city",
            field=models.CharField(
                default="Moscow", max_length=255, verbose_name="город"
            ),
            preserve_default=False,
        ),
    ]
