# Generated by Django 4.2.9 on 2024-04-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_school_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
