# Generated by Django 4.2.9 on 2024-04-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_school_city_alter_school_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school",
            options={"verbose_name": "школа", "verbose_name_plural": "школы"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "verbose_name": "ученик",
                "verbose_name_plural": "ученики",
            },
        ),
    ]
